# Generated by Django 4.1.7 on 2023-05-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("icarus", "0002_rename_users_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="first", new_name="userName",
        ),
        migrations.RemoveField(model_name="user", name="last",),
    ]
