# Generated by Django 4.1.7 on 2023-05-19 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("icarus", "0003_rename_first_user_username_remove_user_last"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="userName", new_name="password",
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
