# Generated by Django 4.1.7 on 2023-06-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("icarus", "0008_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookedFlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.CharField(max_length=50)),
                ("airline", models.CharField(max_length=100)),
                ("departure_time", models.DateTimeField()),
                ("departure_place", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="icarus.user"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="flight", name="destination",),
        migrations.RemoveField(model_name="flight", name="origin",),
        migrations.RemoveField(model_name="passenger", name="flights",),
        migrations.DeleteModel(name="Airport",),
        migrations.DeleteModel(name="Flight",),
        migrations.DeleteModel(name="Passenger",),
    ]
