# Generated by Django 4.1.7 on 2023-06-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icarus", "0009_bookedflight_remove_flight_destination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedflight",
            name="user",
            field=models.CharField(max_length=50),
        ),
    ]
